version = "2.7.4"

maxColumn = 100
rewrite.rules = [AvoidInfix, SortImports, RedundantParens, SortModifiers]
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = JavaDoc
