version = "2.7.4"

maxColumn = 150
rewrite.rules = [SortImports, RedundantParens, SortModifiers]
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = JavaDoc
trailingCommas = multiple
